### ISSUE TITLE
Summary output

### ISSUE THREAD

**Issue by ebhmayra** [bergmanlab/mcclintock#111]
Hi,

I ran Mcclintock2 requiring only some methods (-m); however, when this ended, I didn't get the summary folder. Is there any way to configure Mcclintock2 to get the summary files no matter which methods you require? 

Best,
Mayra

**Comment by cbergman** [comment]
Hi @ebhmayra 

The expected outcome is for McClintock to generate a summary report no matter how many methods are run. For example, if just Relocate2 is run on the test data, then a `summary_report.txt` file is created in `/path/to/output/SRR800842_1/results/summary/data/run/summary_report.txt`

```
(mcclintock) $ more /path/to/output/SRR800842_1/results/summary/data/run/summary_report.txt

----------------------------------
MCCLINTOCK SUMMARY REPORT
----------------------------------
McClintock Version: 2fc3c3367db3fbba903b93fd694cd812365d8b2a

Command:
python3 mcclintock.py  \
	-r test/sacCer2.fasta  \
	-c test/sac_cer_TE_seqs.fasta  \
	-g test/reference_TE_locations.gff  \
	-t test/sac_cer_te_families.tsv  \
	-1 test/SRR800842_1.fastq.gz  \
	-2 test/SRR800842_2.fastq.gz  \
	-p 28  \
	-m relocate2  \
	-o /path/to/output

run from directory: /path/to/mcclintock
Started:    2023-05-08 11:31:20
Completed:  2023-05-08 12:22:43
----------------------------------
MAPPED READ INFORMATION
----------------------------------
read1 sequence length:  101
read2 sequence length:  101
read1 reads:            20316743
read2 reads:            20330624
median insert size:     302
avg genome coverage:    303.023
----------------------------------

-----------------------------------------------------
METHOD          ALL       REFERENCE    NON-REFERENCE
-----------------------------------------------------
ngs_te_mapper   NA        NA           NA
ngs_te_mapper2  NA        NA           NA
relocate        NA        NA           NA
relocate2       135       41           94
temp            NA        NA           NA
temp2           NA        NA           NA
retroseq        NA        NA           NA
popoolationte   NA        NA           NA
popoolationte2  NA        NA           NA
te-locate       NA        NA           NA
teflon          NA        NA           NA
tebreak         NA        NA           NA
-----------------------------------------------------
```

I'm wondering if you job may have exited before completion. Could you please share the command you used for your McClintock run and list the contents of your log directory (e.g. `ls -ltr /path/to/output/logs/*/`)? 

Best regards,
Casey

**Comment by ebhmayra** [comment]
Dear Cassey,

I ran another script and it got the summary file. But I don't know the previous job did not provide the summary. However, when I tried to run the whole group of packages, te-locate failed always for every individual, and relocate and Teflon are very slow.

However, I get new errors apparently related to the conflict between macclintock2 and conda update. I ran the same script before for other individuals and it was oK. I would like to know if you are working to solve this issue.
...
Job counts:
        count   jobs
        1       ngs_te_mapper2_post
        1       ngs_te_mapper2_pre
        1       ngs_te_mapper2_run
        1       setup_reads
        1       summary_report
        5
Traceback (most recent call last):
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.7/site-packages/Bio/Align/__init__.py", line 21, in <module>
    from Bio.Align import _aligners
ImportError: cannot import name '_aligners' from partially initialized module 'Bio.Align' (most likely due to a circular import) (/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.7/site-packages/Bio/Align/__init__.py)

ERROR...unable to locate required external scripts at: /home/apps/conda/miniconda3/envs/mcclintock-2.0.0/share/mcclintock/scripts/ or /home/apps/conda/miniconda3/envs/mcclintock-2.0.0/share/mcclintock/config/preprocessing/
[Wed May 10 21:02:21 2023]
Error in rule setup_reads:
    jobid: 4
    output: /tmp/slurm-6733036/mcclintock_annotations_vieillardBT023/vieillardiiBT023_R1_val_1/intermediate/fastq/vieillardiiBT023_R1_val_1_1.fq, /tmp/slurm-6733036/mcclintock_annotations_vieillardBT023/vieillardiiBT023_R1_val_1/intermediate/fastq/vieillardiiBT023_R1_val_1_2.fq
    conda-env: /home/apps/conda/miniconda3/envs/mcclintock-2.0.0/share/mcclintock/install/envs/conda/10e51870

RuleException:
CalledProcessError in line 37 of /tmp/slurm-6733036/mcclintock_annotations_vieillardBT023/snakemake/6955422/Snakefile:
Command 'source /home/apps/conda/miniconda3/bin/activate '/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/share/mcclintock/install/envs/conda/10e51870'; set -euo pipefail;  python /tmp/slurm-6733036/mcclintock_annotations_vieillardBT023/snakemake/6955422/.snakemake/scripts/tmp7zzin983.setup_reads.py' returned non-zero exit status 1.
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2340, in run_wrapper
  File "/tmp/slurm-6733036/mcclintock_annotations_vieillardBT023/snakemake/6955422/Snakefile", line 37, in __rule_setup_reads
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2352, in run_wrapper
Exiting because a job execution failed. Look above for error message
snakemake --use-conda --conda-prefix /home/apps/conda/miniconda3/envs/mcclintock-2.0.0/share/mcclintock/install/envs/conda --configfile /tmp/slurm-6733036/mcclintock_annotations_vieillardBT023/snakemake/config/config_6955422.json --cores 8 -R --quiet /tmp/slurm-6733036/mcclintock_annotations_vieillardBT023/vieillardiiBT023_R1_val_1/results/ngs_te_mapper2/vieillardiiBT023_R1_val_1_ngs_te_mapper2_nonredundant.bed /tmp/slurm-6733036/mcclintock_annotations_vieillardBT023/vieillardiiBT023_R1_val_1/results/summary/data/run/summary_report.txt
...
Best,
Mayra

**Comment by cbergman** [comment]
Hi @ebhmayra 

Thanks for confirming that you are able to get the expected summary output file from your McClintock run when you only run specific methods. We will look into the potentially new issue that you are experiencing next. 

Can I ask, are you working with @rattei? I ask since an almost identical issue was filed today by this user today: https://github.com/bergmanlab/mcclintock/issues/115. I see that both of these issues are from users using an installation into `/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/`. This is rather coincidental if the two of you are not working together since installation of McClintock following the readme instructions should create the main mcclintock environment in `/home/apps/conda/miniconda3/envs/mcclintock/` not into `/home/apps/conda/miniconda3/envs/mcclintock-2.0.0/`. If you are indeed working together, I will close this current issue and post our solution to your new issue on `https://github.com/bergmanlab/mcclintock/issues/115`.

Thanks,
Casey

**Comment by ebhmayra** [comment]
Hi Casey,

Yes, we work together in this case. 
Thanks, 
Mayra
