### ISSUE TITLE
thanks for making this

### ISSUE THREAD

**Issue by tmcclintock** [bergmanlab/mcclintock#118]
Barbara McClintock was my great aunt, and inspired me to become a scientist. I stumbled on this repo while searching for some of my own work, and I just wanted to reach out and say thanks for creating and maintaining this work! Cheers!

**Comment by cbergman** [comment]
Thanks very much for this inspiring message Tom. Your great aunt founded the entire field of science that my lab and many others work on, so I owe her a lot. I've been a great admirer of her work for a long time, and try to enhance her legacy wherever I can. A long while back, I also named a new transpson family we discovered in Drosophila after her: https://www.ncbi.nlm.nih.gov/nucleotide/AF541948. Thanks again and best of luck with you future endeavors!
