### ISSUE TITLE
Add sample allele frequency information to BED output when available

### ISSUE THREAD

**Issue by cbergman** [bergmanlab/mcclintock#29]
- TEMP and a few other methods provide an estimate of non-reference TE insertion frequency in the raw output
- this information is useful for filtering/analyzing predictions and could be encode in the BED file

**Comment by jensbast** [comment]
would be nice to have this option also for reference TEs

**Comment by shunhuahan** [comment]
- Allele frequency is added to TEMP and PoPoolationTE bed output files, which are the only two methods providing this information in their raw output.
- For TEMP, frequency for reference TEs is always 100% (opposite of absence), which is not useful for interpretation, so I only added frequency for non-reference TEs. For PoPoolationTE, frequency for both reference and non-reference TEs has been added.
