### ISSUE TITLE
Any chance RelocaTE could be replaced with RelocaTE2

### ISSUE THREAD

**Issue by davidecarlson** [bergmanlab/mcclintock#35]
Hi Bergman Lab folks,
Thanks for developing McClintock!  I'm in the process of testing it for us in my research.  While I'm finding it useful, it also looks like RelocaTE is prohibitively slow for moderately sized datasets.  Is there any chance that you could replace RelocaTE with the much faster RelocaTE2 (or simply add it to the workflow)?

See [RelocaTE2 on Github](https://github.com/JinfengChen/RelocaTE2)
Also, here is the [RelocaTE2 paper](https://peerj.com/articles/2942/).  

Just a thought.
Thanks!
Dave

**Comment by shunhuahan** [comment]
Hi Dave,
Thanks for your interest in McClintock. For your kindly suggestion, we are in the process of evaluating whether current component methods should be updated and whether new method should be incorporated into McClintock.
Regrading to RelocaTE issue, we did recognize it when running this method on moderately sized datasets (e.g. from Drosophila melanogaster). Currently, I would suggest excluding RelocaTE when running McClintock on large dataset with many TE families.

Thanks!
Shunhua

**Comment by davidecarlson** [comment]
Thanks, Shunhua!  I look forward to seeing how McClintock develops.  In the meantime, I'll try running it without RelocaTE.

Best,
Dave

**Comment by cbergman** [comment]
- Relocate2 is in bioconda: https://bioconda.github.io/recipes/relocate2/README.html

**Comment by cbergman** [comment]
- RelocaTE2 has been incorporated into an updated version of the McClintock pipeline, which we plan to make available soon.
