### ISSUE TITLE
Error running RelocaTE with test data

### ISSUE THREAD

**Issue by lazydaisy85** [bergmanlab/mcclintock#36]
Hi Bergman Lab, 

Thanks for this pipeline, it was really necessary! I've been running the pipeline with the test data (sacCer2), and I got no results from RelocaTE. Both SRR800842_relocate_nonredundant.bed and SRR800842_relocate_redundant.bed files are empty. 

The errors I got are these (beside subroutine redefined warnings for the module Bio::DB::IndexedBase.pm) :

> Error: The requested bed file (/scratch/bnavarr2/analysis/mcclintock_test/mcclintock/sacCer2/SRR800842/RelocaTE/SRR800842_relocate_presort_redundant.txt) could not be opened. Exiting!
> Error: The requested bed file (/scratch/bnavarr2/analysis/mcclintock_test/mcclintock/sacCer2/SRR800842/RelocaTE/tmp) could not be opened. Exiting!

In the originalmethodsresults folder of RelocaTE, the following files are empty too: 

> not.given.\*.confident_nonref_genomeflanks.fa
> not.given.\*.confident_nonref_reads_list.txt 
> not.given.\*.confident_nonref.txt

Any hints?

**Comment by cbergman** [comment]
Could you post the results of the `sh install.sh` script? I suspect there is an issue with your bioperl installation being picked up by RelocaTE.

**Comment by lazydaisy85** [comment]
That might be right, I've had troubles with it finding some modules. 
Thanks for your prompt response!

[install.mcclintock.out.txt](https://github.com/bergmanlab/mcclintock/files/2202981/install.mcclintock.out.txt)

**Comment by cbergman** [comment]
It looks like bioperl is being picked up in your environment, but our install script does test that your bioperl install is complete. I would try running RelocaTE directly (i.e. outside of McClintock) and see what happens. If RelocaTE can't run directly and gives bioperl-releated errors, then I suspect your bioperl installation is incomplete.

**Comment by cbergman** [comment]
Hi @lazydaisy85. Any luck getting this sorted out? If you have anything to report, please let us know. I'll close this issue in a few days if we don't hear back from you.

**Comment by foriin** [comment]
@cbergman I also have trouble running mcclintock with test data, but, in my case, with popoolTE and RetroSeq. What can I do to investigate? I am trying to run mcclintock on windows 10 bash ubuntu

**Comment by lazydaisy85** [comment]
Hi @foriin and @cbergman ,
I had troubles running PoPoolationTE too. I found out that it is able to run without any problems when you run just the PoPoolationTE pipeline (-m "PoPoolationTE") and save the output in a separate directory rather than where the output of the other modules are, so I guess that for some reason it needs to generate its own references. 
Also, I didn't get it to work without a gff with the reference TE annotation.

**Comment by cbergman** [comment]
- @lazydaisy85  & @foriin - let's try to keep different bug reports in different issues. 
- @lazydaisy85 - can you confirm that you got RelocaTE working on the test data? If so, I will close this issue.
- @foriin - can you open a new issue concerning running on windows 10 bash ubuntu & document your input and output?
- @lazydaisy85 - can you open a new issue concerning running PoPoolationTE & document your input and output?
Thanks!

**Comment by lazydaisy85** [comment]
I did. The reason why Bioperl was not picked up was that the @INC did not contain the the path to my Bioperl installation, so I linked all the modules in one of the folders picked by the @INC and it got RelocaTE to work on the sample data.

Sorry for the delayed update.

**Comment by cbergman** [comment]
No problem, glad to hear this worked. Please note, we've updated the installation instructions to use bionconda to install the base dependencies for the entire system. See the Readme for more information: https://github.com/bergmanlab/mcclintock/blob/master/README.md. This new install procedure should avoid thes sorts of bioperl issues in the future.
