### ISSUE TITLE
Compile papers using McClintock pipeline

### ISSUE THREAD

**Issue by cbergman** [bergmanlab/mcclintock#40]

**Comment by cbergman** [comment]
- Ilyin et al (2017): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5570135/
- Nelson et al (2017) https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5555480/
- Ryazansky et al (2017): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5407775/
- Bergman et al (2017): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5602686/
- Treepong et al (2018): https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/bty479/5040324

**Comment by shunhuahan** [comment]
Goerner-Potvin et al (2018): https://www.nature.com/articles/s41576-018-0050-x

**Comment by cbergman** [comment]
- Duc et al (2019): https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1736-x
- Bast et al (2019): https://elifesciences.org/articles/48548
- Gramazio et al (2019): https://www.frontiersin.org/articles/10.3389/fpls.2019.01220/full
- Vendrell-Mir et al (2019): https://mobilednajournal.biomedcentral.com/articles/10.1186/s13100-019-0197-9
- Kordyukova et al (2020): https://academic.oup.com/nar/article/48/1/141/5625537

**Comment by cbergman** [comment]
- Oggenfuss et al (2020): https://www.biorxiv.org/content/10.1101/2020.02.11.944652v1

**Comment by cbergman** [comment]
- Jiménez‐Ruiz et al: https://acsess.onlinelibrary.wiley.com/doi/full/10.1002/tpg2.20010

**Comment by cbergman** [comment]
- Ilyin et al: https://link.springer.com/article/10.1007/s00412-020-00738-5

**Comment by cbergman** [comment]
- Taylor et al: https://www.biorxiv.org/content/10.1101/2021.05.02.442375v1
- Han et al: https://www.biorxiv.org/content/10.1101/2021.04.24.441253v1

**Comment by cbergman** [comment]
- Han et al (2021): https://www.biorxiv.org/content/10.1101/2021.12.08.471819v1.abstract
- Yan et al (2021): https://www.sciencedirect.com/science/article/pii/S259034622100184X 
- Han et al (2022): https://www.biorxiv.org/content/10.1101/2022.01.04.471818v1.abstract
- Dsaigle et al (2022): https://www.biorxiv.org/content/10.1101/2022.02.02.478770v1

**Comment by cbergman** [comment]
- Navarro-Dominguez et al. (2022): https://elifesciences.org/articles/78981
- Serra et al. (2022): https://academic.oup.com/hr/advance-article/doi/10.1093/hr/uhac111/6586540

**Comment by cbergman** [comment]
- Huang et al (2024): https://www.nature.com/articles/s41467-024-49250-9
