### ISSUE TITLE
mcclintock.sh Segmentation fault  

### ISSUE THREAD

**Issue by mehmetdayi** [bergmanlab/mcclintock#50]
I am trying to use mcclintock tool for TE analysis, but I am receiving several errors below;

This is my command;

~/applications/mcclintock/mcclintock/mcclintock.sh -r SpeciesA.genome.fa -c SpeciesA.consensi.fa.classified -1 DNAreads_1.fastq -I

I am using HPC system, so I don’t have memory problems.

Erros are:

Running McClintock version: b9d86c19b404304a18f4f64592472af97e16d9f4

Date of run is 04_03_20

Creating directory structure...

~/applications/mcclintock/mcclintock/mcclintock.sh: line 216: 54800 Segmentation fault      (core dumped) samtools faidx $referencefolder/$reference_genome_file
cp: cannot stat ‘DNAreads_1.fastq’: No such file or directory
cp: cannot stat ‘DNAreads_1.fastq’: No such file or directory
RepeatMasker::setspecies: Could not find user specified library /lustre6/home/lustre2/user1/Projects/Species/Active_Repeats/SpeciesA/reference/consensi.fa.classified.
sed: can't read /lustre6/home/lustre2/user1/Projects/Species/Active_Repeats/SpeciesA/reference/SpeciesA.genome.fa.out.gff: No such file or directory
index file /lustre6/home/lustre2/user1/Projects/Species/Active_Repeats/SpeciesA/reference/SpeciesA.genome.fa.fai not found, generating...
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
/home/user1/applications/mcclintock/mcclintock/mcclintock.sh: line 488: 74803 Aborted                 (core dumped) bedtools getfasta -name -fi $reference_genome -bed $te_locations -fo $referencefolder/reference_te_seqs.fasta
rm: cannot remove ‘/lustre6/home/lustre2/user1/Projects/Species/Active_Repeats/SpeciesA/reference/SpeciesA.genome.fa.fai’: No such file or directory

Performing FastQC analysis...

Skipping '/lustre6/home/lustre2/user1/Projects/Species/Active_Repeats/SpeciesA/DNAreads_1/reads/Ip1583_1.fastq' which didn't exist, or couldn't be read
/home/user1/applications/mcclintock/mcclintock/mcclintock.sh: line 511: 77039 Segmentation fault      (core dumped) samtools faidx $reference_genome
/home/user1/applications/mcclintock/mcclintock/mcclintock.sh: line 511: 77086 Segmentation fault      (core dumped) samtools faidx $popoolationte_reference_genome
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.4-r385
[main] CMD: bwa index /lustre6/home/lustre2/user1/Projects/Species/Active_Repeats/SpeciesA/reference/SpeciesA.genome.fa
[main] Real time: 0.009 sec; CPU: 0.005 sec
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.4-r385
[main] CMD: bwa index /lustre6/home/lustre2/user1/Projects/Species/Active_Repeats/SpeciesA/reference/popoolationte_full_SpeciesA.fasta
[main] Real time: 0.008 sec; CPU: 0.005 sec

Running RelocaTE pipeline...

/home/user1/applications/mcclintock/mcclintock/mcclintock.sh: line 767: source: deactivate: file not found

**Comment by shunhuahan** [comment]
Hi, can you help me confirm:
- Did you follow the installation instruction in README, especially the part to install dependencies with conda? If you've done that already, did you get any error messages during installation?
https://github.com/bergmanlab/mcclintock/blob/master/README.md
- Are all the input files in the working directory where you run `mcclintock.sh`?
- You provide `-I` to `mcclintock.sh`, which is not a built in argument, is it a typo in the post or in your script?

**Comment by mehmetdayi** [comment]
Hi,

1. Did you follow the installation instruction in README, especially the part to install dependencies with conda? If you've done that already, did you get any error messages during installation?

I haven't received any error. 

2. Are all the input files in the working directory where you run mcclintock.sh?

No, some files (genome and repeat sequences are in another directory). I created a directory and. put reads and called the script from another directory)

3. You provide -I to mcclintock.sh, which is not a built in argument, is it a typo in the post or in your script?

It is a typing error. It was  - i parameter

**Comment by shunhuahan** [comment]
- If the input files are not in the directory where you call the script, then you should provide absolute paths for those files. Can you try that?

**Comment by mehmetdayi** [comment]
I tried and I received same error. It also produced (now and previously) core.numbers files.

**Comment by cbergman** [comment]
- Core dumps suggest that one of the compiled applications that McClintock is running is not compiled or being executed properly on your system. 
- Could you post the exact commands you are using to invoke McClintock and log files (without any modification)?
- Also can you comfirm that you followed the installation instructions exactly as specified in the README?

**Comment by mehmetdayi** [comment]
Running McClintock version: b9d86c19b404304a18f4f64592472af97e16d9f4


Date of run is 07_03_20

Assuming single ended data and launching only ngs_te_mapper and RelocaTE

Creating directory structure...


Calculating normalized average coverage for TEs...


The consensus sequences of the TEs will be used for coverage analysis.

RepeatMasker version open-4.0.7
Search Engine: NCBI/RMBLAST [ 2.9.0+ ]
Master RepeatMasker Database: /home/tk6/applications/RepeatMasker/Libraries/RepeatMaskerLib.embl ( Complete Database: dc20170127-rb20170127 )
Custom Repeat Library: test_mcc_original/Bx/reference/consensi.fa.classified



analyzing file test_mcc_original/Bx/reference/Bx.cov.fasta
identifying matches to consensi.fa.classified sequences in batch 1 of 1344
identifying matches to consensi.fa.classified sequences in batch 2 of 1344
identifying matches to consensi.fa.classified sequences in batch 3 of 1344
identifying matches to consensi.fa.classified sequences in batch 4 of 1344
identifying matches to consensi.fa.classified sequences in batch 5 of 1344
identifying matches to consensi.fa.classified sequences in batch 6 of 1344
identifying matches to consensi.fa.classified sequences in batch 7 of 1344
identifying matches to consensi.fa.classified sequences in batch 8 of 1344
identifying matches to consensi.fa.classified sequences in batch 9 of 1344
identifying matches to consensi.fa.classified sequences in batch 10 of 1344
identifying matches to consensi.fa.classified sequences in batch 11 of 1344
identifying matches to consensi.fa.classified sequences in batch 12 of 1344
identifying matches to consensi.fa.classified sequences in batch 13 of 1344
identifying matches to consensi.fa.classified sequences in batch 14 of 1344
identifying matches to consensi.fa.classified sequences in batch 15 of 1344

###this continues up to 1344.


processing output: 
cycle 1 ..................................................................................................................................
cycle 2 ..................................................................................................................................
cycle 3 ..................................................................................................................................
cycle 4 ..................................................................................................................................
cycle 5 
cycle 6 ..................................................................................................................................
cycle 7 ..................................................................................................................................
cycle 8 .........................................................................................................
cycle 9 .........................................................................................................
cycle 10 .........................................................................................................
Generating output... ........................................................................................................
masking
done
[bwt_gen] Finished constructing BWT in 55 iterations.

Coverage analysis finished.


analyzing file test_mcc_original/Bx/reference/Bx.genome.fa
identifying matches to consensi.fa.classified sequences in batch 1 of 1344
identifying matches to consensi.fa.classified sequences in batch 2 of 1344
identifying matches to consensi.fa.classified sequences in batch 3 of 1344
identifying matches to consensi.fa.classified sequences in batch 4 of 1344
identifying matches to consensi.fa.classified sequences in batch 5 of 1344
identifying matches to consensi.fa.classified sequences in batch 6 of 1344
identifying matches to consensi.fa.classified sequences in batch 7 of 1344
identifying matches to consensi.fa.classified sequences in batch 8 of 1344
identifying matches to consensi.fa.classified sequences in batch 9 of 1344
identifying matches to consensi.fa.classified sequences in batch 10 of 1344
identifying matches to consensi.fa.classified sequences in batch 11 of 1344
identifying matches to consensi.fa.classified sequences in batch 12 of 1344
identifying matches to consensi.fa.classified sequences in batch 13 of 1344
identifying matches to consensi.fa.classified sequences in batch 14 of 1344
identifying matches to consensi.fa.classified sequences in batch 15 of 1344
identifying matches to consensi.fa.classified sequences in batch 16 of 1344
identifying matches to consensi.fa.classified sequences in batch 17 of 1344
identifying matches to consensi.fa.classified sequences in batch 18 of 1344
identifying matches to consensi.fa.classified sequences in batch 19 of 1344
identifying matches to consensi.fa.classified sequences in batch 20 of 1344

####this continues up to 1344

processing output: 
cycle 1 ..................................................................................................................................
cycle 2 ..................................................................................................................................
cycle 3 ..................................................................................................................................
cycle 4 ..................................................................................................................................
cycle 5 
cycle 6 ..................................................................................................................................
cycle 7 ..................................................................................................................................
cycle 8 .........................................................................................................
cycle 9 .........................................................................................................
cycle 10 .........................................................................................................
Generating output... ........................................................................................................
masking
done

Performing FastQC analysis...

[bwt_gen] Finished constructing BWT in 54 iterations.
[bwt_gen] Finished constructing BWT in 65 iterations.

Running RelocaTE pipeline...

test_mcc_original/Bx/reference/Bx.genome.fa does not exist. Check file name.

Removing RelocaTE intermediate files


Running ngs_te_mapper pipeline...

R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.5 (Maipo)

Matrix products: default
BLAS: /usr/lib64/libblas.so.3.4.2
LAPACK: /usr/lib64/liblapack.so.3.4.2

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  base     

loaded via a namespace (and not attached):
[1] compiler_3.4.1

[1] "sample=test_mcc_original/Bx/Ip1583_1/reads/Ip1583_1.fastq"                                    
[2] "genome=test_mcc_original/Bx/reference/Bx.genome.fa"                                           
[3] "teFile=test_mcc_original/Bx/reference/consensi.fa.classified_ID"                              
[4] "tsd=20"                                                                                       
[5] "thread=8"                                                                                     
[6] "output=test_mcc_original/Bx/Ip1583_1/ngs_te_mapper"                                           
[7] "sourceCodeFolder=/lustre7/home/lustre4/mdayi/applications/mcclintock/ngs_te_mapper/sourceCode"
going to analyse: test_mcc_original/Bx/Ip1583_1/reads/Ip1583_1.fastq
in to: test_mcc_original/Bx/Ip1583_1/ngs_te_mapper
with 
        maximum size of TSD: 20
number of thread used: 8
[1] "getting the bwa index for the TE set"
[1] "getting the bwa index for the Genome"

Removing ngs_te_mapper intermediate files


Removing McClintock intermediate files


Pipeline Complete



#####Below is standart error (of HPC run):

Running McClintock version: b9d86c19b404304a18f4f64592472af97e16d9f4


Date of run is 07_03_20


Creating directory structure...

cp: ‘test_mcc_original/Bx/Ip1583_1/reads/Ip1583_1.fastq’: can make relative symbolic links only in current directory
cp: ‘test_mcc_original/Bx/Ip1583_1/reads/Ip1583_1.unPaired.fastq’: can make relative symbolic links only in current directory

Calculating normalized average coverage for TEs...


The consensus sequences of the TEs will be used for coverage analysis.

DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

real    12m58.428s
user    79m23.477s
sys     20m43.527s
[bwa_index] Pack FASTA... 0.62 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=154123722, availableWord=22844512
[BWTIncConstructFromPacked] 10 iterations done. 37682682 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 69614714 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 97991946 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 123209690 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 145619258 characters processed.
[bwa_index] 43.32 seconds elapse.
[bwa_index] Update BWT... 0.45 sec
[bwa_index] Pack forward-only FASTA... 0.48 sec
[bwa_index] Construct SA from BWT and Occ... 20.64 sec
[main] Version: 0.7.4-r385
[main] CMD: bwa index test_mcc_original/Bx/reference/Bx.cov.fasta.masked.aug
[main] Real time: 65.857 sec; CPU: 65.516 sec
[main] Version: 0.7.4-r385
[main] CMD: bwa mem -t 8 -v 0 -R @RG\tID:Ip1583_1\tSM:Ip1583_1 test_mcc_original/Bx/reference/Bx.cov.fasta.masked.aug test_mcc_original/Bx/Ip1583_1/reads/Ip1583_1.fastq
[main] Real time: 0.107 sec; CPU: 0.093 sec
awk: cmd. line:1: fatal: division by zero attempted
(standard_in) 2: syntax error
usage: plot_coverage.py [-h] -a ALL_COV_FILE -u UNIQ_COV_FILE -o OUTPUT_FILE
                        [-n TITLE] [-H PLOT_HEIGHT] [-W PLOT_WIDTH]
                        [--normalize_cov NORMALIZE_COV]
                        [--add_hline ADD_HLINE]
plot_coverage.py: error: argument --normalize_cov: expected one argument
samtools depth: can't parse region "("
samtools depth: can't parse region "("
awk: cmd. line:1: fatal: division by zero attempted
(standard_in) 1: syntax error
usage: plot_coverage.py [-h] -a ALL_COV_FILE -u UNIQ_COV_FILE -o OUTPUT_FILE
                        [-n TITLE] [-H PLOT_HEIGHT] [-W PLOT_WIDTH]
                        [--normalize_cov NORMALIZE_COV]
                        [--add_hline ADD_HLINE]
plot_coverage.py: error: argument --normalize_cov: expected one argument
samtools depth: can't parse region "Recon"
samtools depth: can't parse region "Recon"
awk: cmd. line:1: fatal: division by zero attempted
(standard_in) 1: syntax error
usage: plot_coverage.py [-h] -a ALL_COV_FILE -u UNIQ_COV_FILE -o OUTPUT_FILE
                        [-n TITLE] [-H PLOT_HEIGHT] [-W PLOT_WIDTH]
                        [--normalize_cov NORMALIZE_COV]
                        [--add_hline ADD_HLINE]

##there are many errors related to plot_coverage.py.

lot_coverage.py: error: argument --normalize_cov: expected one argument
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

Coverage analysis finished.


Performing FastQC analysis...

Skipping 'test_mcc_original/Bx/Ip1583_1/reads/Ip1583_1.fastq' which didn't exist, or couldn't be read
[bwa_index] Pack FASTA... 0.49 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=153527324, availableWord=22802588
[BWTIncConstructFromPacked] 10 iterations done. 37613516 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 69486908 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 97812076 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 122983516 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 145351916 characters processed.
[bwa_index] 48.50 seconds elapse.
[bwa_index] Update BWT... 0.46 sec
[bwa_index] Pack forward-only FASTA... 0.33 sec
[bwa_index] Construct SA from BWT and Occ... 26.93 sec
[main] Version: 0.7.4-r385
[main] CMD: bwa index test_mcc_original/Bx/reference/Bx.genome.fa
[main] Real time: 77.040 sec; CPU: 76.723 sec
[bwa_index] Pack FASTA... 0.83 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=198068972, availableWord=25936456
[BWTIncConstructFromPacked] 10 iterations done. 42783148 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 79037836 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 111257068 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 139889564 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 165334188 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 187945420 characters processed.
[bwa_index] 56.58 seconds elapse.
[bwa_index] Update BWT... 0.57 sec
[bwa_index] Pack forward-only FASTA... 0.63 sec
[bwa_index] Construct SA from BWT and Occ... 24.57 sec
[main] Version: 0.7.4-r385
[main] CMD: bwa index test_mcc_original/Bx/reference/popoolationte_full_Bx.fasta
[main] Real time: 83.687 sec; CPU: 83.191 sec

Running RelocaTE pipeline...

DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
runrelocate.sh: line 23: test_mcc_original/Bx/Ip1583_1/../reference/Bxannotation: No such file or directory

use -h option to get help
runrelocate.sh: line 37: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_redundant.bed: No such file or directory
runrelocate.sh: line 38: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_nonredundant.bed: No such file or directory
runrelocate.sh: line 43: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_ref_presort_redundant.txt: No such file or directory
runrelocate.sh: line 44: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_presort_redundant.txt: No such file or directory
runrelocate.sh: line 48: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_presort_redundant.txt: No such file or directory
runrelocate.sh: line 50: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_precut_redundant.txt: No such file or directory
runrelocate.sh: line 51: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_counted_precut_redundant.txt: No such file or directory
runrelocate.sh: line 53: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_redundant.bed: No such file or directory
runrelocate.sh: line 56: test_mcc_original/Bx/Ip1583_1/RelocaTE/tmp: No such file or directory
sort: cannot read: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_counted_precut_redundant.txt: No such file or directory
runrelocate.sh: line 57: test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_nonredundant.bed: No such file or directory
rm: cannot remove ‘test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_counted_precut_redundant.txt’: No such file or directory
rm: cannot remove ‘test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_precut_redundant.txt’: No such file or directory
rm: cannot remove ‘test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_presort_redundant.txt’: No such file or directory
rm: cannot remove ‘test_mcc_original/Bx/Ip1583_1/RelocaTE/tmp’: No such file or directory
rm: cannot remove ‘test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate_ref_presort_redundant.txt’: No such file or directory
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
mv: cannot stat ‘test_mcc_original/Bx/Ip1583_1/RelocaTE/Ip1583_1_relocate*’: No such file or directory
mkdir: cannot create directory ‘test_mcc_original/Bx/Ip1583_1/results/originalmethodresults/RelocaTE’: No such file or directory
cp: cannot stat ‘test_mcc_original/Bx/Ip1583_1/RelocaTE/*/results’: No such file or directory

Removing RelocaTE intermediate files

rm: cannot remove ‘test_mcc_original/Bx/Ip1583_1/RelocaTE’: No such file or directory

Running ngs_te_mapper pipeline...

DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
ls: cannot access test_mcc_original/Bx/reference: No such file or directory
Warning message:
running command 'ls -rt test_mcc_original/Bx/reference' had status 2 
[bwa_index] fail to open file 'test_mcc_original/Bx/reference/consensi.fa.classified_ID'. Abort!
ls: cannot access test_mcc_original/Bx/reference: No such file or directory
Warning message:
running command 'ls -rt test_mcc_original/Bx/reference' had status 2 
[bwa_index] fail to open file 'test_mcc_original/Bx/reference/Bx.genome.fa'. Abort!
mkdir: cannot create directory ‘test_mcc_original/Bx/Ip1583_1/ngs_te_mapper’: File exists
[E::bwa_idx_load] fail to locate the index files
Error in aLength:max(lengths) : result would be too long a vector
Calls: GetSamFile
In addition: Warning messages:
1: running command 'grep -v '^.*[[:space:]]4[[:space:]]\*[[:space:]]0' test_mcc_original/Bx/Ip1583_1/ngs_te_mapper/aligned_te/Ip1583_1.sam' had status 1 
2: In max(lengths) : no non-missing arguments to max; returning -Inf
Execution halted
awk: fatal: cannot open file `test_mcc_original/Bx/Ip1583_1/ngs_te_mapper/bed_tsd/Ip1583_1insertions.bed' for reading (No such file or directory)
Error: The requested bed file (test_mcc_original/Bx/Ip1583_1/ngs_te_mapper/Ip1583_1_ngs_te_mapper_presort.bed) could not be opened. Exiting!
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
mv: cannot move ‘test_mcc_original/Bx/Ip1583_1/ngs_te_mapper/Ip1583_1_ngs_te_mapper_nonredundant.bed’ to ‘test_mcc_original/Bx/Ip1583_1/results/’: Not a directory
mkdir: cannot create directory ‘test_mcc_original/Bx/Ip1583_1/results/originalmethodresults/ngs_te_mapper’: No such file or directory
cp: cannot stat ‘test_mcc_original/Bx/Ip1583_1/ngs_te_mapper/bed_tsd/*.bed’: No such file or directory

Removing ngs_te_mapper intermediate files

unzip:  cannot find or open *.zip, *.zip.zip or *.zip.ZIP.

No zipfiles found.
ls: cannot access test_mcc_original/Bx/Ip1583_1/results/summary/fastqc_analysis/*_1*/fastqc_data.txt: No such file or directory
mcclintock.sh: line 898: test_mcc_original/Bx/Ip1583_1/results/summary/summary_report.txt: No such file or directory
mcclintock.sh: line 1013: test_mcc_original/Bx/Ip1583_1/results/summary/te_summary_table.csv: No such file or directory

Removing McClintock intermediate files

rm: cannot remove ‘test_mcc_original/Bx/Ip1583_1/reads’: No such file or directory
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.

Pipeline Complete


####Finally in output directory:

There are two directories:

Ip1583_1  reference

in Ip1583_1 directory:
there are 4 directories:

bam  reads  results  sam

the bam, reads and sam directories are empty.
the results directory has following :

originalmethodresults  summary  te_coverage

originalmethodresults is empty.
the_coverage has genome_avg_depth  te_cov_plot  te_depth.csv

summary directory has fastqc_analysis  summary_report.txt

fastqc_analysis  is empty. 

The reference directory has following:

Bx.cov.fasta             Bx.cov.fasta.masked.aug.amb  Bx.cov.fasta.out             Bx.genome.fa         Bx.genome.fa.masked      Bx.genome.fa.tbl           popoolationte_full_Bx.fasta      popoolationte_full_Bx.fasta.sa  relocate_te_locations.gff
Bx.cov.fasta.align       Bx.cov.fasta.masked.aug.ann  Bx.cov.fasta.out.gff         Bx.genome.fa.amb     Bx.genome.fa.out         Bx.sorted.genome           popoolationte_full_Bx.fasta.amb  popool_hierarchy.tsv            relocate_te_seqs.fasta
Bx.cov.fasta.bed         Bx.cov.fasta.masked.aug.bwt  Bx.cov.fasta.sorted.bed      Bx.genome.fa.ann     Bx.genome.fa.out.gff     chromosome_names           popoolationte_full_Bx.fasta.ann  popool_te_locations.gff         te_list
Bx.cov.fasta.cat.gz      Bx.cov.fasta.masked.aug.fai  Bx.cov.fasta.tbl             Bx.genome.fa.bwt     Bx.genome.fa.out_HL.gff  consensi.fa.classified     popoolationte_full_Bx.fasta.bwt  popool_te_seqs.fasta            TE-names
Bx.cov.fasta.masked      Bx.cov.fasta.masked.aug.pac  Bx.fasta.out.complement.bed  Bx.genome.fa.cat.gz  Bx.genome.fa.pac         consensi.fa.classified_ID  popoolationte_full_Bx.fasta.fai  reference_TE_locations.bed
Bx.cov.fasta.masked.aug  Bx.cov.fasta.masked.aug.sa   Bx.fasta.out.zero.bed        Bx.genome.fa.fai     Bx.genome.fa.sa          hierarchy.tsv              popoolationte_full_Bx.fasta.pac  reference_te_seqs.fasta


### These are process and outputs when I mcclinkton.sh script.
### I modified source activate and source deactivate by writing the full path of conda activate and conda deactivate (I am using higher version of conda 4), but results are the same.

**Comment by cbergman** [comment]
- Before we proceed, can you directly reply yes or no to the following questions
  - Did you follow the installation instructions exactly as specified in the README?
  - Did you run the test script to ensure your installation is intact?
  - Did the test script complete without errors?
- Once you answer these questions we can try to help you trouble shoot your analysis
- Also, in the future, please (i) redirect your *unmodified* stdout and stderr to files and attach the files to this issue and (ii) provide *the exact unix command* you used to invoke McClintock. It is currently difficult to determine how you are running the system and how much you have edited your output.

**Comment by mehmetdayi** [comment]
I am reinstalling now (although previously I followed the readme)

#This has an error:
git clone git@github.com:bergmanlab/mcclintock.git
Cloning into 'mcclintock'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

## then I copied below.
git clone https://github.com/bergmanlab/mcclintock.git
Cloning into 'mcclintock'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1523 (delta 0), reused 1 (delta 0), pack-reused 1519
Receiving objects: 100% (1523/1523), 515.54 KiB | 796.00 KiB/s, done.
Resolving deltas: 100% (1016/1016), done.

I attached files (installation process, test run output).
[test_run.txt](https://github.com/bergmanlab/mcclintock/files/4314125/test_run.txt)
[installation_process_1.txt](https://github.com/bergmanlab/mcclintock/files/4314128/installation_process_1.txt)
[installation_process_edited.txt](https://github.com/bergmanlab/mcclintock/files/4314129/installation_process_edited.txt)
[envs_installation_process_1.txt](https://github.com/bergmanlab/mcclintock/files/4314130/envs_installation_process_1.txt)
[envs_installation_process_2.txt](https://github.com/bergmanlab/mcclintock/files/4314131/envs_installation_process_2.txt)

## test run was successful. 
## for my data set I used sh mcclintock.1.sh -r Bx.genome.fa -c repeats.fasta -1 Ip1583_1.fastq -2 Ip1583_2.fastq #in the current directory. I just edited source word as conda. without editing it didn't work.

**Comment by mehmetdayi** [comment]
I attached std error and std out results of run in which I used my data.

[bx_test.o.txt](https://github.com/bergmanlab/mcclintock/files/4317566/bx_test.o.txt)
[bx_test.e.txt](https://github.com/bergmanlab/mcclintock/files/4317563/bx_test.e.txt)

**Comment by cbergman** [comment]
- I am still not able to follow what you are doing in terms of your installation since there multiple versions of your installation output files, some that have apparently been edited.
- can I ask for you to uninstall your conda and mcclintock installation and start over and execute the following commands without any modification
```
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME//miniconda.sh
bash ~/miniconda.sh -b -p $HOME/miniconda # silent mode
echo "export PATH=\$PATH:\$HOME/miniconda/bin" >> $HOME/.bashrc # add to .bashrc
source $HOME/.bashrc

conda update conda
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda

git clone git@github.com:bergmanlab/mcclintock.git
cd mcclintock
sh env_install.sh

sh install.sh

cd test
sh runtest.sh
```
- Then, please attach the stdout and stderr as one file each
- If you experience an error, please do not make any modifications to any of the scripts or the stderr/stdout files. Rather report the error and output without any modification (so that it can be reproduced) and we can try to help you get to the next step in your debugging. Currently, there are too many manual operations that you are performing for us to diagnose what is going on.

**Comment by mehmetdayi** [comment]
## I tried to get McClintock, but it didn't work as below. 

```
git clone git@github.com:bergmanlab/mcclintock.git
Cloning into 'mcclintock'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

This is why I had to download from another link (`git clone https://github.com/bergmanlab/mcclintock.git`) that worked.

Briefly, 
What I modified is to replace "`source`" in env_install.sh and install.sh with "`conda`", because I am using another version of conda which gives an error during `env_install.sh` . 

Another modification that I did is the same thing in `install.sh` and `mcclintoch.sh`. Then, the installation and test run worked.

##with new conda, miniconda3 (in my local computer).
I downloaded and tried to install without any modification. Below is an error of env_install.sh

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
env_install.sh: line 37: deactivate: No such file or directory
