### ISSUE TITLE
The fasta consensus set of TE sequences

### ISSUE THREAD

**Issue by YTLogos** [bergmanlab/mcclintock#57]
Hi, Thanks for developing such a great pipeline to detect TE insertions. I am just confused about the fasta consensus set of TE sequences. Is it mean the consensus sequence of each TE or each TE family? And could you please give some advice how to construct the consensus sequence! THX
Tao

**Comment by cbergman** [comment]
Hi @YTLogos -

McClintock expects that the user provides 1 representative sequence per TE family. This can either be a consensus sequence derived from multiple copies in the genome, or a "canonical" sequence from one element that could have been isolated from experimental methods.

Constructing consensus TE sequences de novo from a genome is a challenging exercise and is an active area of research. Typically people use systems like RepeatModeller to do this. Answering this fully is outside the scope of the McClintock project. Please have a look at posts on Biostars to see if there are any tips on how you can create your consensus TE library.

Best regards,
Casey
