### ISSUE TITLE
git error (fatal: not a git repository (or any of the parent directories): .git)

### ISSUE THREAD

**Issue by tomaszjacek** [bergmanlab/mcclintock#75]
Hi,
I have successfully installed pipeline on conda container and downloaded data.
but when try to run  command

python3 mcclintock.py \
    -r /work/mcclintock/test/sacCer2.fasta \
    -c /work/mcclintock/test/sac_cer_TE_seqs.fasta \
    -g /work/mcclintock/test/reference_TE_locations.gff \
    -t /work/mcclintock/test/sac_cer_te_families.tsv \
    -1 /data/mcclintock/test/SRR800842_1.fastq.gz \
    -2 /data/mcclintock/test/SRR800842_2.fastq.gz \
    -p 10 \
    -o /data/mcclintock/test/output/

I got the error

(mcclintock) root@014812dbbbbc:/work/mcclintock# sh runPipelineForTest.sh
SETUP            checking fasta: /work/mcclintock/test/sacCer2.fasta
SETUP            checking fastq: /data/mcclintock/test/SRR800842_1.fastq.gz
SETUP            checking fastq: /data/mcclintock/test/SRR800842_2.fastq.gz
SETUP            checking fasta: /work/mcclintock/test/sac_cer_TE_seqs.fasta
SETUP            checking locations gff: /work/mcclintock/test/reference_TE_locations.gff
SETUP            checking taxonomy TSV: /work/mcclintock/test/sac_cer_te_families.tsv
fatal: not a git repository (or any of the parent directories): .git
git rev-parse HEAD

could you give me a hand with this??

Thank you,
tj

**Comment by pbasting** [comment]
Hi @tomaszjacek thanks for reporting this issue,
* An early step of mcclintock tries to determine which version of mcclintock you are using by getting the git commit hash from your mcclintock directory using `git rev-parse HEAD`.
* The error is claiming the the directory in which you have mcclintock installed is not a git repository. 
* Can you describe how you installed mcclintock? If you used `git clone` as described in the README this shouldn't happen, but I can see this being a problem if you downloaded the source code via the `Download ZIP` option. 
* I intended for the `git rev-parse HEAD` step to be optional, and if it fails the pipeline was meant to continue on without knowledge of the version, but it appears my error handling is bugged so I'll need to fix that.
* For now, if you install mcclintock via: `git clone git@github.com:bergmanlab/mcclintock.git` (as described: https://github.com/bergmanlab/mcclintock#-installing-mcclintock) you shouldn't have this error.
* Let me know if this resolves the issue, I'll work on fixing the error handling for this step so if it occurs again the pipeline should continue without knowing the version.

**Comment by tomaszjacek** [comment]
I have downloaded zip file because the command on webpage was not working for me
>git clone git@github.com:bergmanlab/mcclintock.git
>fatal: Could not read from remote repository.

now I cloned repo with command
git clone https://github.com/bergmanlab/mcclintock.git
and the error "not a git repository" does not show up now

but pipeline gives me a another error

MissingInputException in line 1 of /work/mcclintock/snakefiles/telocate.snakefile:
Missing input files for rule telocate_taxonomy:
/work/mcclintock/install/tools/te-locate/TE_hierarchy.pl

Thank you,
tj

**Comment by pbasting** [comment]
* Ok great that `git clone https://github.com/bergmanlab/mcclintock.git` worked. Now the error you are getting is due to te-locate (and likely the other component methods) not being installed yet
* This can be done by fist running `python3 mcclintock.py --install`
* After running the install, you should then be able to run the pipeline, let me know if you run into any other errors

-Preston

**Comment by tomaszjacek** [comment]
Yes its working now,
(I forgot that after replacing 'mcclintock' folder I need to run installation again....)
I have noticed that after installation the container is 8.4Gb bigger... I'm curious which one of pipeline software is so heavy??


Thank you!
tj

**Comment by pbasting** [comment]
* Great! now that it is working, I am going to close this issue. Feel free to open a new one if anything else comes up.
##
Regarding the size of mcclintock after installation:
* ~ 3.6 GB is coming from the test data fastq files (`test/`) so you can remove those if you are done testing mcclintock. They can be re-downloaded in the future via `python3 test/download_test_data.py`. 
* The bulk of the rest of the size comes from the conda environments. Each method has their own set of dependencies, many of which are incompatible with the dependencies of other tools, so to be safe and compartmentalized, each tool has it's own conda environment containing it's own dependencies which vary in size depending on the size/number of dependencies.
* Based on my installation, none of the method's conda environments are vastly different in size than the others, with them all being roughly 100MB-700MB each.
 * If you are only interested in running a subset of the component methods available in mcclintock, you can run `python3 mcclintock.py --install -m <tool1>,<tool2>` to only install the specific methods you are interested in. Just know that this will delete the installations of the non-specified tools and if you try to run methods that aren't installed you will get an error
