### ISSUE TITLE
Error trying to execute glpsol

### ISSUE THREAD

**Issue by acontrerasg** [bergmanlab/mcclintock#79]
Hello,

I have a small problem running the pipeline with my data.

I installed  the tool through conda and run the test  with no issues. But then when I apply it to my custom genome and my custom TE library I see this error after trim_galore successfully runs:

`
 File "/conda_envs/mcclintock/lib/python3.7/site-packages/snakemake/__init__.py", line 735, in snakemake
    keepincomplete=keep_incomplete,
  File "/conda_envs/mcclintock/lib/python3.7/site-packages/snakemake/workflow.py", line 972, in execute
    success = scheduler.schedule()
  File "/conda_envs/mcclintock/lib/python3.7/site-packages/snakemake/scheduler.py", line 406, in schedule
    else self.job_selector_ilp(needrun)
  File "/conda_envs/mcclintock/lib/python3.7/site-packages/snakemake/scheduler.py", line 625, in job_selector_ilp
    prob.solve()
  File "/conda_envs/mcclintock/lib/python3.7/site-packages/pulp/pulp.py", line 1899, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/conda_envs/mcclintock/lib/python3.7/site-packages/pulp/apis/glpk_api.py", line 81, in actualSolve
    raise PulpSolverError("PuLP: Error while trying to execute "+self.path)
pulp.apis.core.PulpSolverError: PuLP: Error while trying to execute glpsol`

Any idea what may have contributed to the error?

Thank you for your time,
Adrián

**Comment by pbasting** [comment]
Hi @acontrerasg , 

Thanks for the bug report, to narrow down the cause of the issue, can you post the package list for your mcclintock environment?
You should be able to get the list of packages by:
```
conda activate mcclintock
conda list
```
* This way I can see what version of pulp and snakemake is installed so I can try an replicate this error.

Thanks!
Preston

**Comment by acontrerasg** [comment]
Hi @pbasting ,
Thanks for  looking at it. 

The version of Pulp is 
pulp                      2.3.1            py37hc8dfbb8_0    conda-forge

Here is the full list of packages:
[mcclintock_env_list.txt](https://github.com/bergmanlab/mcclintock/files/5868433/mcclintock_env_list.txt)

Best,
Adrián

**Comment by pbasting** [comment]
* Thanks @acontrerasg It looks like we are using the same pulp build and snakemake build so that shouldn't be the problem. 
* I noticed in the snakemake change log that for snakemake 5.26.1 (https://snakemake.readthedocs.io/en/stable/project_info/history.html#id23) they changed the default solver due to errors with GLPK (probably like what you are experiencing). So the solution may be to update the default mcclintock env to use a newer version of snakemake. 
* I'll test out mcclintock with a newer version of snakemake to see if it works. I'll let you know when I've made the changes in the master branch so you can see if they resolve your issues.

-Preston

**Comment by pbasting** [comment]
* Hi @acontrerasg 
* With the most recent commit: https://github.com/bergmanlab/mcclintock/commit/28d688289dfbf8586de3604023e12ec728214711 I've updated the mcclintock env yaml to use the newest version of snakemake.
* You will have to do a clean install with this commit including recreating the `mcclintock` environment.
```
conda env create -f install/envs/mcclintock.yml --name mcclintock
conda activate mcclintock
python3 mcclintock.py --install
```
* This should hopefully resolve the solver errors you were experiencing. Let me know if you still are having issues

-Preston
