### ISSUE TITLE
Failed to solve scheduling problem with ILP solver

### ISSUE THREAD

**Issue by ch8316f5eyu** [bergmanlab/mcclintock#82]
Hi, 
when I run mcclintock, this error occured:
```
PROCESSING       making coverage fasta
PROCESSING       coverage fasta created
PROCESSING       making reference fasta
PROCESSING       making consensus fasta
PROCESSING       consensus fasta created
PROCESSING       prepping reads for McClintock
PROCESSING       formatting the name of consensus TE fasta headers for compatibility with relocaTE
PROCESSING       relocaTE consensus fasta created
PROCESSING       reference fasta created
PROCESSING       adding fake chromosomes if chrom # < 5, required by TE-locate
PROCESSING       making samtools and bwa index files for reference fasta &> /home/data/gmb23/project/Primed_Naive_exon/mcclintock/logs/20210209.165111.9765619/processing.log
PROCESSING       Running RepeatMasker for RelocaTE2 &> /home/data/gmb23/project/Primed_Naive_exon/mcclintock/logs/20210209.165111.9765619/processing.log
PROCESSING       TE-locate reference created
PROCESSING       creating 2bit file from reference genome fasta &> /home/data/gmb23/project/Primed_Naive_exon/mcclintock/logs/20210209.165111.9765619/processing.log
PROCESSING       reference 2bit file created
Failed to solve scheduling problem with ILP solver. Falling back to greedy solver.Run Snakemake with --verbose to see the full solver output for debugging the problem.
PROCESSING       running trim_galore &> /home/data/gmb23/project/Primed_Naive_exon/mcclintock/logs/20210209.165111.9765619/trimgalore.log
[INFO   ]         multiqc : This is MultiQC v1.9 (043bffd)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/data/gmb23/project/Primed_Naive_exon/mcclintock/ESC_Naive_R1/results/trimgalore
[INFO   ]        cutadapt : Found 2 reports
[INFO   ]          fastqc : Found 2 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
PROCESSING       read setup complete
NGS_TE_MAPPER2   running ngs_te_mapper2 &> /home/data/gmb23/project/Primed_Naive_exon/mcclintock/logs/20210209.165111.9765619/ngs_te_mapper2.log
PROCESSING       samtools and bwa index files for reference fasta created
Failed to solve scheduling problem with ILP solver. Falling back to greedy solver.Run Snakemake with --verbose to see the full solver output for debugging the problem.
```
I have no idea what is it and how to solve it.

**Comment by pbasting** [comment]
Hi @ch8316f5eyu,

The `Failed to solve scheduling problem with ILP solver` is not a fatal error. It is just a message from snakemake stating that the ILP solver failed and that it will use the greedy solver instead. I have yet to see the greedy solver fail on any of my runs. McClintock should run fine despite this warning message. Try letting the job run to completion even if you see this message. If any other errors occur, let me know.

Thanks,

Preston

**Comment by ch8316f5eyu** [comment]
Hi @pbasting 
This is the new error:
`python /home/data/gmb23/app/mcclintock/install/tools/teflon/teflon_prep_annotation.py -wd /home/data/gmb23/project/Primed_Naive_exon/mcclintock/ESC_Naive_R1/results/teflon/unfiltered/ -a /home/data/gmb23/project/Primed_Naive_exon/mcclintock/ESC_Naive_R1/results/teflon/unfiltered/reference_te.bed -t /home/data/gmb23/project/Primed_Naive_exon/mcclintock/ESC_Naive_R1/results/teflon/unfiltered/teflon_taxonomy.tsv -f /home/data/gmb23/project/Primed_Naive_exon/mcclintock/GRCm38.primary_assembly.genome/consensus_fasta/consensusTEs.fasta -g /home/data/gmb23/project/Primed_Naive_exon/mcclintock/GRCm38.primary_assembly.genome/genome_fasta/GRCm38.primary_assembly.genome.fasta -p teflon
[Wed Feb 10 22:39:47 2021]
Error in rule teflon_preprocessing:
    jobid: 12
    output: /home/data/gmb23/project/Primed_Naive_exon/mcclintock/ESC_Naive_R1/results/teflon/unfiltered/reference_te.bed, /home/data/gmb23/project/Primed_Naive_exon/mcclintock/ESC_Naive_R1/results/teflon/unfiltered/teflon_taxonomy.tsv, /home/data/gmb23/project/Primed_Naive_exon/mcclintock/ESC_Naive_R1/results/teflon/unfiltered/teflon.sorted.bam
    conda-env: /home/data/gmb23/app/mcclintock/install/envs/conda/f3368e68

RuleException:
CalledProcessError in line 25 of /home/data/gmb23/app/mcclintock/snakefiles/teflon.snakefile:
Command 'source /home/data/gmb23/miniconda3/envs/mcclintock/bin/activate '/home/data/gmb23/app/mcclintock/install/envs/conda/f3368e68'; set -euo pipefail;  /home/data/gmb23/miniconda3/envs/mcclintock/bin/python3.7 /home/data/gmb23/project/Primed_Naive_exon/mcclintock/snakemake/9765619/.snakemake/scripts/tmpvkpxvwjq.teflon_pre.py' returned non-zero exit status 1.
  File "/home/data/gmb23/miniconda3/envs/mcclintock/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2340, in run_wrapper
  File "/home/data/gmb23/app/mcclintock/snakefiles/teflon.snakefile", line 25, in __rule_teflon_preprocessing
  File "/home/data/gmb23/miniconda3/envs/mcclintock/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/data/gmb23/miniconda3/envs/mcclintock/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/data/gmb23/miniconda3/envs/mcclintock/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/data/gmb23/miniconda3/envs/mcclintock/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2352, in run_wrapper
COVERAGE         augmenting reference genome
COVERAGE         samtools and bwa indexing reference &> /home/data/gmb23/project/Primed_Naive_exon/mcclintock/logs/20210209.165111.9765619/coverage.log
COVERAGE         samtools and bwa indexing reference &> /home/data/gmb23/project/Primed_Naive_exon/mcclintock/logs/20210209.165111.9765619/coverage.log
`
Thank you for your help

**Comment by pbasting** [comment]
Hi @ch8316f5eyu,

* It looks like something is going wrong with the TEFLoN preprocessing module but I'll need to see the TEFLoN log to try and determine what is happening. 
* Can you attach your teflon log to a post on this issue so that I can look through it? Based on the log you posted, it should be at: `/home/data/gmb23/project/Primed_Naive_exon/mcclintock/logs/20210209.165111.9765619/teflon.log`

Thanks!
-Preston
