### ISSUE TITLE
How to install tools manually ?

### ISSUE THREAD

**Issue by wyj-lzu** [bergmanlab/mcclintock#94]
Hi

When I run python3 mcclintock.py --install, it successfully installed the tools excepted [popoolationte]. And then I run python3 mcclintock.py --install -m popoolationte, I got the error like this:

INSTALL          installing dependencies
INSTALL          WARNING: this could take awhile
INSTALL          Removing existing conda env for: popoolationte
INSTALL          Installing scripts for:popoolationte
Job counts:
	count	jobs
	1	popoolationte
	1
downloading  http://downloads.sourceforge.net/project/popoolationte/popoolationte_1.02.zip to /home/ug0134/Software/mcclintock/install/tools/popoolationte.zip
(<class 'urllib.error.URLError'>, URLError(timeout('timed out')), <traceback object at 0x7ff692cefa00>)
download failed...
downloading  http://downloads.sourceforge.net/project/popoolationte/popoolationte_1.02.zip to /home/ug0134/Software/mcclintock/install/tools/popoolationte.zip
(<class 'urllib.error.URLError'>, URLError(timeout('timed out')), <traceback object at 0x7ff69252ed70>)
download failed...
downloading  http://downloads.sourceforge.net/project/popoolationte/popoolationte_1.02.zip to /home/ug0134/Software/mcclintock/install/tools/popoolationte.zip
(<class 'urllib.error.URLError'>, URLError(timeout('timed out')), <traceback object at 0x7ff692534140>)
download failed...
popoolationte download failed... exiting...
try running --install with --clean for clean installation
[Fri May 20 10:47:49 2022]
Error in rule popoolationte:
    jobid: 0
    output: /home/ug0134/Software/mcclintock/install/tools/popoolationte/identify-te-insertsites.pl
    conda-env: /home/ug0134/Software/mcclintock/install/envs/conda/60a348e4

RuleException:
CalledProcessError in line 135 of /home/ug0134/Software/mcclintock/install/Snakefile:
Command 'source /home/ug0134/.conda/envs/mcclintock/bin/activate '/home/ug0134/Software/mcclintock/install/envs/conda/60a348e4'; set -euo pipefail;  /home/ug0134/.conda/envs/mcclintock/bin/python3.7 /home/ug0134/Software/mcclintock/install/.snakemake/scripts/tmptl9n55dt.popoolationte.py' returned non-zero exit status 1.
  File "/home/ug0134/.conda/envs/mcclintock/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2340, in run_wrapper
  File "/home/ug0134/Software/mcclintock/install/Snakefile", line 135, in __rule_popoolationte
  File "/home/ug0134/.conda/envs/mcclintock/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/home/ug0134/.conda/envs/mcclintock/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/ug0134/.conda/envs/mcclintock/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/home/ug0134/.conda/envs/mcclintock/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2352, in run_wrapper
Exiting because a job execution failed. Look above for error message
snakemake --use-conda --conda-frontend=mamba --conda-prefix /home/ug0134/Software/mcclintock/install//envs/conda --configfile/home/ug0134/Software/mcclintock/install//config.json --cores 1 --nolock /home/ug0134/Software/mcclintock/install/tools/popoolationte/identify-te-insertsites.pl --quiet

It seems that a timed out error happened when download the sofeware. I try to install it manually but I failed. How can I fix it ?

Bests,
Yinjia

**Comment by cbergman** [comment]
Hi @wyj-lzu 

Thanks for your issue report. This seems like a URL accessibility issue for the popoolationte zip, possibly because Sourceforge was down or blocked when you tried to install McClintock. Can you try testing if the popoolationte zip can be downloaded directly as follows and report back here?

```
wget http://downloads.sourceforge.net/project/popoolationte/popoolationte_1.02.zip
```
If a direct download works on your end, then it may be a different issue. 

Thanks,
Casey

**Comment by wyj-lzu** [comment]
Hi,

I run it two days later and it run successfully. : )

Bests,
Yinjia

**Comment by cbergman** [comment]
Thanks for the update, looks like this was a temporary sourceforge download issue.
