### ISSUE TITLE
KeyError: 'ngs_te_mapper2'

### ISSUE THREAD

**Issue by jingydz** [bergmanlab/mcclintock#98]
## command
> $python3 mcclintock.py \
>     -r test/sacCer2.fasta \
>     -c test/sac_cer_TE_seqs.fasta \
>     -g test/reference_TE_locations.gff \
>     -t test/sac_cer_te_families.tsv \
>     -1 test/SRR800842_1.fastq.gz \
>     -2 test/SRR800842_2.fastq.gz \
>     -p 4 \
>     -o test_output
Traceback (most recent call last):
  File "/data/yulab/zhangjj/software/mcclintock/mcclintock.py", line 886, in <module>
    main()
  File "/data/yulab/zhangjj/software/mcclintock/mcclintock.py", line 33, in main
    check_installed_modules(args.methods, sysconfig.NO_INSTALL_METHODS, config_install.MD5, os.path.dirname(os.path.abspath(__file__))+"/install/")
  File "/data/yulab/zhangjj/software/mcclintock/mcclintock.py", line 444, in check_installed_modules
    if installed_version[method] != method_md5s[method]:
KeyError: 'ngs_te_mapper2'
## command
> $ ngs_te_mapper2
usage: ngs_te_mapper2 [-h] -f READS -l LIBRARY -r REFERENCE [-a ANNOTATION] [-w WINDOW] [--min_mapq MIN_MAPQ] [--min_af MIN_AF] [--tsd_max TSD_MAX] [--gap_max GAP_MAX] [-m MAPPER]
                      [-t THREAD] [-o OUT] [-p PREFIX] [-k]
ngs_te_mapper2: error: the following arguments are required: -f/--reads, -l/--library, -r/--reference

Hi, I get this error when I test this software, is there a problem with the version of my 'ngs_te_mapper2' software?

**Comment by cbergman** [comment]
Hi @jingydz 

From what I can tell from your issue report, it looks like when your installation of McClintock is testing that components are installed properly (using the check_installed_modules function on line 33) you are getting mismatch between the md5 computed for ngs_te_mapper2 and the expected md5 for ngs_te_mapper2 (found here: https://github.com/bergmanlab/mcclintock/blob/master/internal/install.py#L25). I would completely remove your current installation and do a clean installation following the instructions here: https://github.com/bergmanlab/mcclintock#install. Please pay attention to whether you get any warnings or errors after you run `python3 mcclintock.py --install`. If the re-installation is clean, try the test command you posted above. Please report back after you've tried these steps.

Thanks,
Casey

**Comment by cbergman** [comment]
Hi @jingydz

Were you able to solve this problem by doing a clean installation? If so, could you please let us know so we can close this issue?

Thanks,
Casey

**Comment by cbergman** [comment]
Hi @jingydz

Since we haven't heard back from you, I'm going to close this issue. Please feel free to comment further if you are still experiencing and issue with your McClintock installation.

Best regards,
Casey
